Astina\RedirectManagerBundle\Entity\Map:
    type: entity
    table: armb_redirect_map
    repositoryClass: Astina\RedirectManagerBundle\Entity\MapRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        urlFrom:
            type: string
            unique: true
            length: 255
        urlTo:
            type: string
            length: 255
        count:
            type: integer
    lifecycleCallbacks: {  }
