Astina\Bundle\RedirectManagerBundle\Entity\Map:
    type: entity
    table: armb_redirect_map
    repositoryClass: Astina\Bundle\RedirectManagerBundle\Entity\MapRepository
    uniqueConstraints:
        hostPattern_urlFrom: { columns: [hostPattern, urlFrom] }
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        hostPattern:
            type: string
            length: 255
            nullable: true
        urlFrom:
            type: string
            length: 255
        urlTo:
            type: string
            length: 255
        count:
            type: integer
        countRedirects:
            type: boolean
        redirectHttpCode:
            type: string
            length: 3
    manyToOne:
        group:
            targetEntity: Astina\Bundle\RedirectManagerBundle\Entity\Group
            joinColumn: { onDelete: "set null" }
    lifecycleCallbacks: {  }
