armb_homepage:
    pattern:  /
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:index }

armb_new_map:
    pattern:  /new
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:new }

armb_edit_map:
    pattern:  /{id}/edit
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:edit }

armb_update_map:
    pattern:  /{id}/update
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:update }
    requirements:
        _method:  POST

armb_delete_map:
    pattern:  /{id}/delete
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:delete }
    requirements:
        _method:  POST
