armb_homepage:
    path:  /
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:index }

armb_new_map:
    path:  /new
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:new }

armb_edit_map:
    path:  /{id}/edit
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:edit }

armb_delete_map:
    path:  /{id}/delete
    defaults: { _controller: AstinaRedirectManagerBundle:Mapping:delete }
    methods:  [POST]

armg_group_new:
    path: /group/new
    defaults: { _controller: AstinaRedirectManagerBundle:Group:form }

armg_group_edit:
    path: /group/{id}/edit
    defaults: { _controller: AstinaRedirectManagerBundle:Group:form }

armg_group_delete:
    path: /group/{id}/delete
    defaults: { _controller: AstinaRedirectManagerBundle:Group:delete }
    methods:  [POST]
