parameters:
    armb.redirect.class: Astina\Bundle\RedirectManagerBundle\EventListener\RedirectListener
    armb.service.csv_importer: Astina\Bundle\RedirectManagerBundle\Service\CsvImporter
    armb.redirect_finder.class: Astina\Bundle\RedirectManagerBundle\Service\RedirectFinder

services:
    armb.router:
        class: %armb.redirect.class%
        arguments: [@armb.redirect_finder]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 512 }
    armb.csv_importer:
        class: %armb.service.csv_importer%
        arguments: [@doctrine]
    armb.redirect_finder:
        class: %armb.redirect_finder.class%
        arguments: [@doctrine]