parameters:
    armb.redirect.class: Astina\RedirectManagerBundle\EventListener\RedirectListener

services:
    armb.router:
        class: %armb.redirect.class%
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
