Astina\Bundle\RedirectManagerBundle\Entity\Map:
    properties:
        urlFrom:
            - NotBlank: ~
        urlTo:
            - NotBlank: ~

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [ host, urlFrom ]

Astina\Bundle\RedirectManagerBundle\Entity\Group:
    properties:
        name:
            - NotBlank: ~
        priority:
            - NotBlank: ~
