language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

env:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.1.*"

before_script:
    - phpenv config-rm xdebug.ini
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install --dev
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash

script:
  - phpunit
