language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

env:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.1.*"

before_install:
    - composer selfupdate
    - phpenv config-rm xdebug.ini
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    - echo memory_limit = -1 >> $INI_FILE

install:
    - composer install --dev
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script:
  - phpunit
